Repository GoogleChromeLabs/quicklink, pull requests merged in 2023-04, with the labels that each got.

#321 Update ESLint to v8 and add eslint-plugin-react
  .eslintrc.js
  package-lock.json
  package.json
  src/react-chunks.js
Labels: dependencies, squash

#330 site: move meta charset first
  site/src/_includes/layouts/head.njk
Labels: docs, squash

#328 site: remove the unused highlightjs preload and `noscript` fallback
  site/src/_includes/layouts/head.njk
Labels: docs, squash

#331 site: update HTML minifier's options
  site/.eleventy.js
Labels: docs, squash

#318 Replace mocha with uvu
  package-lock.json
  package.json
  test/bootstrap.js
  test/quicklink.spec.js
Labels: enhancement, dependencies, squash

#333 site: remove IE-related icons
  site/.eleventy.js
  site/src/_includes/layouts/head.njk
  site/src/assets/images/icons/mstile-150x150.png
  site/src/browserconfig.xml
Labels: docs, squash

#332 site: remove unneeded type from script
  site/src/_includes/layouts/base.njk
Labels: docs, squash

#338 Update react.njk from README.md
  site/src/_includes/components/react.njk
Labels: docs, squash

#312 Lint tweaks
  .eslintrc.js
  src/chunks.mjs
  src/index.mjs
  src/prefetch.mjs
  src/prerender.mjs
  src/react-chunks.js
  src/request-idle-callback.mjs
  test/quicklink.spec.js
Labels: squash

#337 site: compress SVG files with the latest svgo (v3.0.2)
  site/src/assets/images/graphs/prefetch-improve-svgomg.svg
  site/src/assets/images/graphs/prefetch-quicklink-svgomg.svg
  site/src/assets/images/graphs/prefetching.svg
  site/src/assets/images/graphs/what-is-prefetch-svgomg.svg
  site/src/assets/images/logos/angular.svg
  site/src/assets/images/logos/drupal.svg
  site/src/assets/images/logos/magento.svg
  site/src/assets/images/logos/quicklink.svg
  site/src/assets/images/logos/react.svg
  site/src/assets/images/logos/vue.svg
  site/src/assets/images/logos/wordpress.svg
Labels: docs, squash

#334 site: fix github-fork/star label
  site/src/_includes/components/github-fork.njk
  site/src/_includes/components/github-star.njk
Labels: docs, squash

#329 site: change prism theme to okaidia
  site/src/styles/prism.css
Labels: docs, squash

#324 site: update devDependencies
  site/package-lock.json
  site/package.json
Labels: docs, squash

#323 site: specify loading lazy for more images
  site/src/_includes/components/github-fork.njk
  site/src/_includes/components/github-star.njk
  site/src/_includes/components/use-with.njk
  site/src/demo.njk
  site/src/measure.njk
Labels: docs, squash

#339 Update quicklink.svg from site
  assets/images/logos/quicklink.svg
Labels: docs, squash

#340 site: lazyload font icons too and add height too
  site/src/_includes/components/download.njk
Labels: docs, squash

#341 approach.njk: use inline code in a couple of cases
  site/src/approach.njk
Labels: docs, squash

#327 site: Backport fixes from README
  README.md
  site/src/_includes/components/react.njk
  site/src/api.njk
Labels: docs, squash

#319 Move test fixtures to a subfolder
  CONTRIBUTING.md
  demos/basic.html
  demos/hrefFn/hrefFn_demo.html
  demos/network-idle.html
  test/fixtures/1.html
  test/fixtures/2.html
  test/fixtures/3.html
  test/fixtures/4.html
  test/fixtures/index.html
  test/fixtures/main.css
  test/fixtures/rmanifest.json
  test/fixtures/test-allow-origin-all.html
  test/fixtures/test-allow-origin.html
  test/fixtures/test-basic-usage.html
  test/fixtures/test-custom-dom-source.html
  test/fixtures/test-custom-href-function.html
  test/fixtures/test-delay.html
  test/fixtures/test-es-modules.html
  test/fixtures/test-ignore-basic.html
  test/fixtures/test-ignore-multiple.html
  test/fixtures/test-limit.html
  test/fixtures/test-node-list.html
  test/fixtures/test-prefetch-chunks.html
  test/fixtures/test-prefetch-duplicate-shared.html
  test/fixtures/test-prefetch-duplicate.html
  test/fixtures/test-prefetch-multiple.html
  test/fixtures/test-prefetch-single.html
  test/fixtures/test-prerender-andPrefetch.html
  test/fixtures/test-prerender-only.html
  test/fixtures/test-prerender-wrapper-multiple.html
  test/fixtures/test-prerender-wrapper-single.html
  test/fixtures/test-same-origin.html
  test/fixtures/test-threshold.html
  test/fixtures/test-throttle.html
  test/quicklink.spec.js
Labels: squash

#345 Update minor devDependencies
  package-lock.json
  package.json
  site/package-lock.json
  site/package.json
Labels: dependencies

#349 README.md: fix redirects
  README.md
Labels: docs, squash

#342 README.md: switch a white background banner
  README.md
  assets/images/logos/banner-white-bg.png
Labels: docs

#314 site: compress binary images
  site/src/assets/images/icons/android-chrome-192x192.png
  site/src/assets/images/icons/android-chrome-512x512.png
  site/src/assets/images/icons/apple-touch-icon.png
  site/src/assets/images/icons/favicon-32x32.png
  site/src/assets/images/quicklink-used-logos/barefootwine.ca.png
  site/src/assets/images/quicklink-used-logos/hartfordwines.com.png
  site/src/assets/images/quicklink-used-logos/hashnode.com.png
  site/src/assets/images/quicklink-used-logos/matsuda.com.png
  site/src/assets/images/quicklink-used-logos/newegg.com.png
  site/src/assets/images/quicklink-used-logos/oakley.com.png
  site/src/assets/images/quicklink-used-logos/quiply.com.png
  site/src/assets/images/quicklink-used-logos/rayban.com.png
  site/src/assets/images/quicklink-used-logos/saintagnes.org.png
  site/src/assets/images/quicklink-used-logos/syfy.com.png
  site/src/assets/images/quicklink-used-logos/vinyla.com.png
  site/src/assets/images/quicklink-used-logos/week.co.jp.png
  site/src/assets/images/screenshots/devtools-optimized-1.png
  site/src/assets/images/screenshots/devtools-optimized-2.png
  site/src/assets/images/screenshots/devtools-unoptimized.png
  site/src/assets/images/screenshots/spa-devtools-optimized-1.png
  site/src/assets/images/screenshots/spa-devtools-optimized-2.png
  site/src/assets/images/screenshots/wpt-metrics-comparison.png
  site/src/assets/images/screenshots/wpt-video-comparison.gif
  site/src/assets/images/screenshots/wpt-visual-comparison.png
Labels: docs

#278 Add another option for magento module
  README.md
Labels: docs, squash

#378 site: add a robots.txt file
  site/src/robots.njk
Labels: docs

#372 site: move csspreload.js to an include
  .eslintignore
  package.json
  site/src/_includes/js/vendor/cssrelpreload.js
  site/src/_includes/layouts/head.njk
Labels: docs, squash

#380 site: trim clipboard text
  site/src/script.js
Labels: docs

#371 site: switch to @11ty/eleventy-navigation
  site/.eleventy.js
  site/package-lock.json
  site/package.json
  site/src/_data/site.json
  site/src/_includes/layouts/header.njk
  site/src/api.njk
  site/src/approach.njk
  site/src/demo.njk
  site/src/index.njk
  site/src/measure.njk
Labels: docs

#373 site: switch to using `EleventyHtmlBasePlugin`
  site/.eleventy.js
  site/src/_includes/layouts/base.njk
  site/src/_includes/layouts/head.njk
  site/src/_includes/layouts/header.njk
Labels: docs

#377 site: move styles and js to assets
  site/.eleventy.js
  site/package.json
  site/src/_includes/layouts/base.njk
  site/src/_includes/layouts/head.njk
  site/src/assets/js/script.js
  site/src/assets/styles/copy-snippet.css
  site/src/assets/styles/footer.css
  site/src/assets/styles/github-markdown.css
  site/src/assets/styles/github-markdown.min.css
  site/src/assets/styles/main.css
  site/src/assets/styles/prism.css
Labels: docs, squash

#375 site: move og-image to the repo
  site/src/_data/site.json
  site/src/_includes/layouts/head.njk
  site/src/assets/images/og-image.png
Labels: docs

#376 site: specify loading=lazy for "Use With" images
  site/src/_includes/components/use-with.njk
Labels: docs

#384 site: streamline docs from README.md
  README.md
  demos/network-idle.html
  demos/news-workbox/README.md
  demos/news/README.md
  demos/spa/README.md
  site/src/api.njk
Labels: docs

#374 site: fix `og:url` and remove `twitter:site`
  site/src/_includes/layouts/head.njk
Labels: docs

#386 site: split head.njk to partials
  site/src/_includes/layouts/favicons.njk
  site/src/_includes/layouts/head.njk
  site/src/_includes/layouts/social.njk
Labels: docs

#381 site: switch to prism tomorrow theme
  site/src/assets/styles/prism.css
Labels: docs

#362 site: add missing `alt` attributes to `img` elements
  site/src/demo.njk
  site/src/measure.njk
Labels: docs, squash
